[package]
name = "infra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contracts = { path = "../contracts" }
async-trait = "0.1.52"
tracing = "0.1.19"
tracing-futures = "0.2.0"
rdkafka = "0.28.0"